variable "engine" {}
variable "subnets" {}
variable "name" {}
variable "env" {}
#variable "nodes" {}
#variable "skip_final_snapshot" {}
#variable "vpc_id" {}
#variable "BASTION_NODE" {}
#variable "vpc_cidr" {}
#variable "PROMETHEUS_NODE" {}